project:
  type: website

website:
  # title: "Zero to Quarto"
  # navbar:
  #   left:
  #     - href: main.qmd
  #       text: Main
  #     - href: about.qmd
  #       text: About
  
  sidebar:
    - title: "Zero to Quarto"
      contents:
        - index.md
        - section: "Subjects"
          contents:
          - content/folder-structure.md
          - content/terminal.md
          - content/path-variable.md
          - content/vscode.md
          - content/markdown.md
          - content/git.md
          - content/python.md
          - content/virtual-environments.md
          - content/jupyter.qmd
          - content/quarto.qmd

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    code-fold: true

jupyter: python3
