project:
  type: website

website:
  # title: "Zero to Quarto"
  # navbar:
  #   left:
  #     - href: main.qmd
  #       text: Main
  #     - href: about.qmd
  #       text: About
  
  sidebar:
    - title: "Zero to Quarto"
      contents:
        - home.md
        - section: "Lessons"
          contents:
          - content/folder-structure.md
          - content/terminal.md
          - content/python.qmd
          - content/quarto.qmd
          - content/path-variable.qmd
          - content/vscode.md

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    code-fold: true

jupyter: python3
