project:
  type: website
  render:
  - README.md
  - "*.qmd"
  - "*.md"

website:
  # title: "Zero to Quarto"
  # navbar:
  #   left:
  #     - href: main.qmd
  #       text: Main
  #     - href: about.qmd
  #       text: About
  
  sidebar:
    - title: "Zero to Quarto"
      contents:
        - README.md
        - section: "Hour 1: A Preview"
          contents:
          - content/z00.previews.md
        - section: "Further content"
          contents:
          - content/z01.vscode.md
          - content/z02.markdown.md
          - content/z02.z01.file-extensions.md
          - content/z02.z02.binary-vs-plain-text.md
          - content/z02.z03.data-file-formats.md
          - content/z03.git.md
          - content/z03.z01.github.md
          - content/z04.python-in-colab.md
          - content/z05.folder-structure.md
          - content/z06.terminal.md
          - content/z07.path-variable.md
          - content/z08.python.md
          - content/z09.virtual-environments.md
          - content/z10.jupyter.md
          - content/z11.interactive-python.md
          - content/z12.quarto.qmd
        - section: "Building a Package"
          contents:
          - content/z13.building-a-package.md
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-fold: true

jupyter: python3
