project:
  type: website
  render:
  - README.md
  - "*.qmd"
  - "*.md"

website:
  # title: "Zero to Quarto"
  # navbar:
  #   left:
  #     - href: main.qmd
  #       text: Main
  #     - href: about.qmd
  #       text: About
  
  sidebar:
    - title: "Zero to Quarto"
      contents:
        - README.md
        - section: "Hour 0: Prerequisites"
          contents:
          - content/z00.z02.prerequisites.md
        - section: "Hour 1: A Preview"
          contents:
          - content/z00.z03.previews.md
          - content/z00.z05.this-site.md
          - content/z00.z06.playgrounds.md
        - section: "Hour 2: Running Python Online"
          contents:
          - content/z00.z07.python-in-google-colab.md
          - content/z00.z08.python-in-a-file.md
          - content/z00.z09.python-in-a-terminal.md
        - section: "Hour 3: Setting Up Your Local Environment"
          contents:
          - content/z01.vscode.md
          - content/z02.markdown.md
          - content/z02.z01.files-and-folders.md
          - content/z06.terminal.md
          - content/z07.path-variable.md
        - section: "Hour 4: Working Together"
          contents:
          - content/z07.z05.git.md
          - content/z07.z06.github.md
        - section: "Hour 5: Running Python Locally"
          contents:
          - content/z08.python.md
          - content/z09.virtual-environments.md
          - content/z10.jupyter.md
          - content/z11.interactive-python.md
          - content/z11.z05.building-a-package.md
        - section: "Hour X: Quarto"
          contents:
          - content/z12.quarto.qmd
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-fold: true

jupyter: python3
