project:
  type: website

website:
  title: "Zero to Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: main.qmd
        text: Main
      - href: about.qmd
        text: About
  
  sidebar:
    - title: "Main"
      contents:
        - main.qmd
        - folder-structure.qmd
        - terminal.qmd

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    code-fold: true

jupyter: python3
